"""rename type to geometry_type

Revision ID: 53aab384b99a
Revises: 
Create Date: 2018-06-06 21:40:06.577173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53aab384b99a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer', sa.Column('geometry_type', sa.String(length=20), nullable=True))
    op.drop_column('layer', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer', sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('layer', 'geometry_type')
    # ### end Alembic commands ###
