"""layerview table

Revision ID: 6998056be233
Revises: 79a55f0817ce
Create Date: 2018-05-30 20:37:01.500474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6998056be233'
down_revision = '79a55f0817ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('layerview',
    sa.Column('layerview_id', sa.Integer(), nullable=False),
    sa.Column('layer_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('pointtolayer', sa.String(length=256), nullable=True),
    sa.Column('style', sa.String(length=256), nullable=True),
    sa.Column('oneachfeature', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['layer_id'], ['layer.layer_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.PrimaryKeyConstraint('layerview_id')
    )
    op.drop_table('layers2projects')
    op.create_index(op.f('ix_layer_name'), 'layer', ['name'], unique=True)
    op.drop_column('layer', 'pointtolayer')
    op.drop_column('layer', 'style')
    op.drop_column('layer', 'oneachfeature')
    op.create_index(op.f('ix_project_name'), 'project', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_name'), table_name='project')
    op.add_column('layer', sa.Column('oneachfeature', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('layer', sa.Column('style', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('layer', sa.Column('pointtolayer', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_layer_name'), table_name='layer')
    op.create_table('layers2projects',
    sa.Column('layer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['layer_id'], ['layer.layer_id'], name='layers2projects_layer_id_fkey'),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], name='layers2projects_project_id_fkey'),
    sa.PrimaryKeyConstraint('layer_id', 'project_id', name='layers2projects_pkey')
    )
    op.drop_table('layerview')
    # ### end Alembic commands ###
